config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check

  resources :user
  resources :consultations

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :user
  # has_one :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :consultations
  # has_one :randomizer?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  # before_action : authenticate_user ??

  def index
    # @consultations = current_user.consultations
    @consultations = Consultation.all
  end

  def new
    # @consultation = current_user.consultations.new
    @consultation = Consultation.new
  end

  def create
    # @consultation = current_user.consultations.new(consultation_params)
    @consultation = Consultations.new(consultation_params)
    @consultation.date = Date.today
    if @consultation.save
      redirect_to consultations_path
    else
      flash.now[:alert] = "Failed to create consultation."
      render :new, status: :unprocessable_entity
    end
  end

  # should also update?

  private

  def consultation_params
    params.require(:consultation).permit(:name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/consultations/index.html.erb
<h1>Current Consultations:</h1>

<div class="consultcardcontainer">

  <% @consultations.each do |consultation| %>
    <div class="consultation-card">
      <h2><%= consultation.name %></h2>
    </div>
  <% end %>

</div>

<div class="consultationindex">
 <%= link_to "Create new", new_consultation_path, class: "btn btn-outline-primary btn-sm", style: "border-radius:12px;" %>
</div>

app/views/consultations/new.html.erb
<h1> New Consultation </h1>

<%# do we want buttons and categories for the user to choose from?
and then let them describe? %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZuH4reZGamingConsultancy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/consultation.erb
<h1>Current Consultations:</h1>

<div class="consultcardcontainer"></div>
<div class="consultcard"></div>
<div class="consultcardcontent"></div>

app/views/pages/consultations.erb
<h1>Current Consultations:</h1>

<div class="consultcardcontainer"></div>
<div class="consultcard"></div>
<div class="consultcardcontent"></div>

app/views/pages/home.html.erb
<h1>ZuH4reZ.- Gaming Consultancy</h1>
<h2>Your start of a Journey</h2>

<div class="consultationindex">
 <%= link_to "Consultations", consultations_path, class: "btn btn-outline-primary btn-sm", style: "border-radius:12px;" %>
</div>